### ISSUE TITLE
请教大神

### ISSUE THREAD

**Issue by yeekelly** [rookres/ZYNQ_webserver#1]
你好，我最近在学习嵌入式web的相关知识，有许多疑问，可以交流交流吗？

**Comment by rookres** [comment]
我也是小白,也是在起步阶段,其实我这算不上嵌入式web吧

**Comment by yeekelly** [comment]
你里面写的点亮led灯这些我都还不太懂

**Comment by rookres** [comment]
点灯什么的是属于Linux驱动里面的,在移植好的系统上进行操作,和我这个上传的这个webserver没啥必然联系,这个也可以直接在虚拟机上运行。

**Comment by yeekelly** [comment]
那么，通过webserver实现点亮led灯，除了html文件和cgi程序，还需要led的驱动吗？

**Comment by rookres** [comment]
需要,led驱动才是核心,一般不需要手写,设备树写好就行了.,html和cgi完全就是锦上添花,我就是搞完驱动后,觉得可以这样试下,然后就试了下

**Comment by yeekelly** [comment]
驱动不需要手写吗？我看了某点原子的资料，驱动都是自己写的。如果不手写，如何运用设备树写？

**Comment by rookres** [comment]
把那资料看完你就知道了，其实我这个webserver是Linux的上层应用,我是觉得移植完系统得在板子做些什么,才写的webserver,其实完全没必要

**Comment by yeekelly** [comment]
好的，多谢大神指导，希望以后有不懂的地方还能交流。
